export H_ACCOUNT_URI="https://api.habemus.io/account/v2" \
export H_PROJECT_URI="https://api.habemus.io/project/v1" \
export H_WEBSITE_URI="https://api.habemus.io/website/v1" \
export H_WORKSPACE_URI="https://api.habemus.io/workspace/v1" \
export WEBSITE_HOST="habemus.xyz" \
export WORKSPACE_PREVIEW_HOST="habemus.co" \
export UI_WORKSPACE_BASE_URL="http://habemus.io" \
export UI_DASHBOARD_URI="http://habemus.io/dashboard" \
export LANGUAGES_BASE_URL="/static/editor/languages" \
export DEMO_MODE="enabled"